
// This file was auto-generated by ML.NET Model Builder. 

using EmotionClassification;

// Create single instance of sample data from first line of dataset for model input
EmotionClassificationModel.ModelInput sampleData = new EmotionClassificationModel.ModelInput()
{
    Text = @"suntik vitamin brapa",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


Console.WriteLine($"Label: {@"NOEMOTION"}");
Console.WriteLine($"Text: {@"suntik vitamin brapa"}");


var sortedScoresWithLabel = EmotionClassificationModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

